CONVERT_TO=helios
PIN_COMPATIBLE = promicro

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

MOUSEKEY_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_DIAMETER_MM = 35
CIRQUE_PINNACLE_ATTENUATION	= EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X
CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_ABSOLUTE_MODE