# Base config
RGBLIGHT_ENABLE = no # Disable LED backlighting
LTO_ENABLE = yes  # Makes hex file smaller
OLED_ENABLE = yes # Enable OLEDs
WPM_ENABLE = yes  # Enable word per minute counter
SPLIT_WPM_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
CIRQUE_PINNACLE_DIAMETER_MM = 35
CIRQUE_PINNACLE_ATTENUATION	= EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X
CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_ABSOLUTE_MODE
